vim.pack.add({
	'https://github.com/vague2k/vague.nvim' ,
	'https://github.com/lewis6991/gitsigns.nvim' ,
	'https://github.com/github/copilot.vim' ,
	'https://github.com/kylechui/nvim-surround' ,
	'https://github.com/brenoprata10/nvim-highlight-colors' ,
	'https://github.com/stevearc/oil.nvim' ,
	'https://github.com/nvim-treesitter/nvim-treesitter' ,
	'https://github.com/mbbill/undotree' ,
	'https://github.com/tpope/vim-fugitive' ,
	'https://github.com/echasnovski/mini.pick' ,
	"https://github.com/j-hui/fidget.nvim",

	'https://github.com/neovim/nvim-lspconfig',
	"https://github.com/williamboman/mason.nvim",
	"https://github.com/williamboman/mason-lspconfig.nvim",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/hrsh7th/cmp-buffer",
	"https://github.com/hrsh7th/cmp-path",
	"https://github.com/hrsh7th/cmp-cmdline",
	"https://github.com/hrsh7th/nvim-cmp",
	"https://github.com/L3MON4D3/LuaSnip",
	"https://github.com/saadparwaiz1/cmp_luasnip",
})
